apiVersion: v1
kind: Namespace
metadata:
  name: epalabeling
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epalabeling-data
  namespace: epalabeling
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epalabeling
  namespace: epalabeling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epalabeling
  template:
    metadata:
      labels:
        app: epalabeling
    spec:
      containers:
        - name: epalabeling
          image: createiflabs/epalabeling:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: epalabeling-data
---
apiVersion: v1
kind: Service
metadata:
  name: epalabeling
  namespace: epalabeling
spec:
  type: ClusterIP
  selector:
    app: epalabeling
  ports:
    - name: http
      port: 80
      targetPort: 5000
---
# Traefik CRD (IngressRoute). Voraussetzung: Traefik CRDs sind installiert.
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: epalabeling
  namespace: epalabeling
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`epalabeling.createif-labs.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: epalabeling
          port: 80
